spring.application.name=chess
server.error.path=/error
server.error.include-stacktrace=never
server.error.include-message=always
spring.data.mongodb.uri=${MONGO_URI:null}
spring.data.mongodb.database=chess
