spring.application.name=chess
server.error.path=/error
server.error.include-stacktrace=never
server.error.include-message=always
spring.data.mongodb.uri=mongodb+srv://testuser:TestUser%40mongodb1%403%24@cluster0.kg4kksu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=chess
